// export const ROOMS_MICROSERVICE = 'ROOMS_MICROSERVICE';
// export const TRANSACTIONS_MICROSERVICE = 'TRANSACTIONS_MICROSERVICE';
// export const COLLABORATORS_MICROSERVICE = 'COLLABORATORS_MICROSERVICE';

export const TRANSACTIONS_KAFKA_CLIENT = 'TRANSACTIONS_KAFKA_CLIENT';
export const ROOMS_CLIENT_KAFKA = 'ROOMS_CLIENT_KAFKA';
